# Generated by Django 4.2 on 2025-08-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('department_id', models.CharField(max_length=100)),
                ('department_hod_name', models.CharField(max_length=200)),
                ('department_hod_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='mid1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co', models.CharField(default='1', max_length=5)),
                ('courseoutcome', models.CharField(max_length=100)),
                ('knowledge_level', models.CharField(default='K1', max_length=5)),
                ('k1', models.CharField(max_length=50)),
                ('k2', models.CharField(max_length=50)),
                ('k3', models.CharField(max_length=50)),
                ('k4', models.CharField(max_length=50)),
                ('totalmarks', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=15)),
                ('batch', models.CharField(default='-', max_length=20)),
                ('academicyear', models.CharField(default='-', max_length=20)),
                ('programme', models.CharField(default='-', max_length=20)),
                ('semester', models.CharField(default='-', max_length=20)),
                ('section', models.CharField(default='-', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='mid2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co', models.CharField(default='1', max_length=5)),
                ('courseoutcome', models.CharField(max_length=100)),
                ('knowledge_level', models.CharField(default='K1', max_length=5)),
                ('k1', models.CharField(max_length=50)),
                ('k2', models.CharField(max_length=50)),
                ('k3', models.CharField(max_length=50)),
                ('k4', models.CharField(max_length=50)),
                ('totalmarks', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=15)),
                ('batch', models.CharField(default='-', max_length=20)),
                ('academicyear', models.CharField(default='-', max_length=20)),
                ('programme', models.CharField(default='-', max_length=20)),
                ('semester', models.CharField(default='-', max_length=20)),
                ('section', models.CharField(default='-', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='sem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co', models.CharField(default='1', max_length=5)),
                ('courseoutcome', models.CharField(max_length=100)),
                ('knowledge_level', models.CharField(default='K1', max_length=5)),
                ('k1', models.CharField(max_length=50)),
                ('k2', models.CharField(max_length=50)),
                ('k3', models.CharField(max_length=50)),
                ('k4', models.CharField(max_length=50)),
                ('totalmarks', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=15)),
                ('batch', models.CharField(default='-', max_length=20)),
                ('academicyear', models.CharField(default='-', max_length=20)),
                ('programme', models.CharField(default='-', max_length=20)),
                ('semester', models.CharField(default='-', max_length=20)),
                ('section', models.CharField(default='-', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Userform',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('DateofJoinning', models.DateField()),
                ('Biometricid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('permission', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='UName',
            new_name='User_Name',
        ),
        migrations.AddField(
            model_name='co_pso_matrix',
            name='academicyear',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='co_pso_matrix',
            name='batch',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='co_pso_matrix',
            name='programme',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='co_pso_matrix',
            name='section',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='co_pso_matrix',
            name='semester',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='course_end_survey',
            name='academicyear',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='course_end_survey',
            name='batch',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='course_end_survey',
            name='programme',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='course_end_survey',
            name='section',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='course_end_survey',
            name='semester',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='courseoutcomes',
            name='academicyear',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='courseoutcomes',
            name='batch',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='courseoutcomes',
            name='programme',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='courseoutcomes',
            name='section',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='courseoutcomes',
            name='semester',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dept_id',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hod',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='details_of_instructors',
            name='academicyear',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='details_of_instructors',
            name='batch',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='details_of_instructors',
            name='programme',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='details_of_instructors',
            name='semester',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='lectureplan',
            name='academicyear',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='lectureplan',
            name='batch',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='lectureplan',
            name='programme',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='lectureplan',
            name='section',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='lectureplan',
            name='semester',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='referencebooks',
            name='academicyear',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='referencebooks',
            name='batch',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='referencebooks',
            name='programme',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='referencebooks',
            name='section',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='referencebooks',
            name='semester',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='targetproficiency',
            name='academicyear',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='targetproficiency',
            name='batch',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='targetproficiency',
            name='programme',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='targetproficiency',
            name='section',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='targetproficiency',
            name='semester',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='teachers',
            name='academicyear',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='teachers',
            name='batch',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='teachers',
            name='programme',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='teachers',
            name='section',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='teachers',
            name='semester',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='textbooks',
            name='academicyear',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='textbooks',
            name='batch',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='textbooks',
            name='programme',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='textbooks',
            name='section',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='textbooks',
            name='semester',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='details_of_instructors',
            name='section',
            field=models.CharField(default='-', max_length=10),
        ),
    ]
