# Generated by Django 4.2 on 2023-08-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeapp', '0003_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dept_id',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hod',
            field=models.BooleanField(default=False),
        ),
    ]
