# Generated by Django 4.2 on 2023-08-17 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obeapp', '0004_customuser_dept_id_customuser_hod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='UName',
            new_name='User_Name',
        ),
    ]
