# Generated by Django 4.2 on 2023-08-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeapp', '0006_mid1_mid2_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='co_pso_matrix',
            name='academicyear',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='co_pso_matrix',
            name='batch',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='co_pso_matrix',
            name='programme',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='co_pso_matrix',
            name='section',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='co_pso_matrix',
            name='semester',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='course_end_survey',
            name='academicyear',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='course_end_survey',
            name='batch',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='course_end_survey',
            name='programme',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='course_end_survey',
            name='section',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='course_end_survey',
            name='semester',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='courseoutcomes',
            name='academicyear',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='courseoutcomes',
            name='batch',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='courseoutcomes',
            name='programme',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='courseoutcomes',
            name='section',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='courseoutcomes',
            name='semester',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='details_of_instructors',
            name='academicyear',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='details_of_instructors',
            name='batch',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='details_of_instructors',
            name='programme',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='details_of_instructors',
            name='semester',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='lectureplan',
            name='academicyear',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='lectureplan',
            name='batch',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='lectureplan',
            name='programme',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='lectureplan',
            name='section',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='lectureplan',
            name='semester',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='mid1',
            name='academicyear',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='mid1',
            name='batch',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='mid1',
            name='programme',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='mid1',
            name='section',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='mid1',
            name='semester',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='mid2',
            name='academicyear',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='mid2',
            name='batch',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='mid2',
            name='programme',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='mid2',
            name='section',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='mid2',
            name='semester',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='referencebooks',
            name='academicyear',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='referencebooks',
            name='batch',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='referencebooks',
            name='programme',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='referencebooks',
            name='section',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='referencebooks',
            name='semester',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='sem',
            name='academicyear',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='sem',
            name='batch',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='sem',
            name='programme',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='sem',
            name='section',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='sem',
            name='semester',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='targetproficiency',
            name='academicyear',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='targetproficiency',
            name='batch',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='targetproficiency',
            name='programme',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='targetproficiency',
            name='section',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='targetproficiency',
            name='semester',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='teachers',
            name='academicyear',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='teachers',
            name='batch',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='teachers',
            name='programme',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='teachers',
            name='section',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='teachers',
            name='semester',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='textbooks',
            name='academicyear',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='textbooks',
            name='batch',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='textbooks',
            name='programme',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='textbooks',
            name='section',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='textbooks',
            name='semester',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='details_of_instructors',
            name='section',
            field=models.CharField(default='-', max_length=10),
        ),
    ]
